### ISSUE TITLE
what's the abbr dictionary

### ISSUE THREAD

**Issue by jhqian0909** [ppannuto/python-abbreviate#2]
Could you tell us what the abbr dictionary you are using? Is it a public and general one?

**Comment by ppannuto** [comment]
This is it: https://github.com/ppannuto/python-abbreviate/blob/master/abbreviate/resources/abbreviations/en_US.abbr

Otherwise it's all heuristics, which were basically just delete vowels if memory serves. This project is long dead, so I'm going to archive it. Feel free to take whatever's useful from it though.
